apiVersion: v1
kind: Service
metadata:
  name: soil-service
  namespace: farm-eco
spec:
  selector:
    app: soil
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
