apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: farm-eco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        image: auth-api:latest
        ports:
        - containerPort: 8080
