apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: farm-eco
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
