apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: farm-eco
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
